[2025-03-30T01:44:14.401+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T01:44:14.640+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_data_pipeline.verify_data scheduled__2025-03-30T01:43:00+00:00 [queued]>
[2025-03-30T01:44:14.657+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_data_pipeline.verify_data scheduled__2025-03-30T01:43:00+00:00 [queued]>
[2025-03-30T01:44:14.697+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-30T01:44:14.721+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): verify_data> on 2025-03-30 01:43:00+00:00
[2025-03-30T01:44:14.735+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=931) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-30T01:44:14.739+0000] {standard_task_runner.py:72} INFO - Started process 933 to run task
[2025-03-30T01:44:14.739+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_data_pipeline', 'verify_data', 'scheduled__2025-03-30T01:43:00+00:00', '--job-id', '351', '--raw', '--subdir', 'DAGS_FOLDER/Gestioncommands.py', '--cfg-path', '/tmp/tmpsggv322z']
[2025-03-30T01:44:14.741+0000] {standard_task_runner.py:105} INFO - Job 351: Subtask verify_data
[2025-03-30T01:44:14.823+0000] {task_command.py:467} INFO - Running <TaskInstance: ecommerce_data_pipeline.verify_data scheduled__2025-03-30T01:43:00+00:00 [running]> on host 778b271a0247
[2025-03-30T01:44:14.965+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='ecommerce_data_pipeline' AIRFLOW_CTX_TASK_ID='verify_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T01:43:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T01:43:00+00:00'
[2025-03-30T01:44:14.968+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-30T01:44:14.970+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-30T01:44:14.970+0000] {logging_mixin.py:190} INFO - Current task name:verify_data state:running start_date:2025-03-30 01:44:14.641043+00:00
[2025-03-30T01:44:14.971+0000] {logging_mixin.py:190} INFO - Dag name:ecommerce_data_pipeline and current dag run status:running
[2025-03-30T01:44:14.972+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T01:44:14.973+0000] {Gestioncommands.py:207} INFO - Verifying database content...
[2025-03-30T01:44:15.005+0000] {Gestioncommands.py:228} ERROR - Verification failed: Parser Error: syntax error at or near "FROM"
[2025-03-30T01:44:15.007+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Gestioncommands.py", line 208, in verify_data
    with duckdb.connect(DB_PATH) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Gestioncommands.py", line 210, in verify_data
    raw_tables = conn.execute("SHOW TABLES FROM raw").fetchall()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.ParserException: Parser Error: syntax error at or near "FROM"
[2025-03-30T01:44:15.034+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-30T01:44:15.036+0000] {logging_mixin.py:190} INFO - Task start:2025-03-30 01:44:14.641043+00:00 end:2025-03-30 01:44:15.033450+00:00 duration:0.392407
[2025-03-30T01:44:15.037+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): verify_data> dag:<DAG: ecommerce_data_pipeline> dagrun:<DagRun ecommerce_data_pipeline @ 2025-03-30 01:43:00+00:00: scheduled__2025-03-30T01:43:00+00:00, state:running, queued_at: 2025-03-30 01:44:00.804016+00:00. externally triggered: False>
[2025-03-30T01:44:15.038+0000] {logging_mixin.py:190} INFO - Failure caused by Parser Error: syntax error at or near "FROM"
[2025-03-30T01:44:15.038+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=ecommerce_data_pipeline, task_id=verify_data, run_id=scheduled__2025-03-30T01:43:00+00:00, execution_date=20250330T014300, start_date=20250330T014414, end_date=20250330T014415
[2025-03-30T01:44:15.083+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T01:44:15.084+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 351 for task verify_data (Parser Error: syntax error at or near "FROM"; 933)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Gestioncommands.py", line 208, in verify_data
    with duckdb.connect(DB_PATH) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Gestioncommands.py", line 210, in verify_data
    raw_tables = conn.execute("SHOW TABLES FROM raw").fetchall()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.ParserException: Parser Error: syntax error at or near "FROM"
[2025-03-30T01:44:15.117+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-30T01:44:15.157+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T01:44:15.160+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
