[2025-03-30T12:43:00.015+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T12:43:00.228+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_data_pipeline.load_refined manual__2025-03-30T12:42:50.019425+00:00 [queued]>
[2025-03-30T12:43:00.243+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_data_pipeline.load_refined manual__2025-03-30T12:42:50.019425+00:00 [queued]>
[2025-03-30T12:43:00.255+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-30T12:43:00.274+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_refined> on 2025-03-30 12:42:50.019425+00:00
[2025-03-30T12:43:00.284+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=792) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-30T12:43:00.287+0000] {standard_task_runner.py:72} INFO - Started process 801 to run task
[2025-03-30T12:43:00.287+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_data_pipeline', 'load_refined', 'manual__2025-03-30T12:42:50.019425+00:00', '--job-id', '746', '--raw', '--subdir', 'DAGS_FOLDER/Gestioncommands.py', '--cfg-path', '/tmp/tmp26cidrdp']
[2025-03-30T12:43:00.289+0000] {standard_task_runner.py:105} INFO - Job 746: Subtask load_refined
[2025-03-30T12:43:00.350+0000] {task_command.py:467} INFO - Running <TaskInstance: ecommerce_data_pipeline.load_refined manual__2025-03-30T12:42:50.019425+00:00 [running]> on host 778b271a0247
[2025-03-30T12:43:00.466+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecommerce_data_pipeline' AIRFLOW_CTX_TASK_ID='load_refined' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T12:42:50.019425+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T12:42:50.019425+00:00'
[2025-03-30T12:43:00.468+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-30T12:43:00.469+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-30T12:43:00.470+0000] {logging_mixin.py:190} INFO - Current task name:load_refined state:running start_date:2025-03-30 12:43:00.229719+00:00
[2025-03-30T12:43:00.471+0000] {logging_mixin.py:190} INFO - Dag name:ecommerce_data_pipeline and current dag run status:running
[2025-03-30T12:43:00.472+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T12:43:00.473+0000] {Gestioncommands.py:108} INFO - Mise à jour des tables transformées...
[2025-03-30T12:43:00.511+0000] {Gestioncommands.py:227} ERROR - Erreur de transformation : Catalog Error: Schema with name refined does not exist!
[2025-03-30T12:43:00.513+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Gestioncommands.py", line 110, in load_refined
    with duckdb.connect(DB_PATH) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Gestioncommands.py", line 112, in load_refined
    conn.execute("""
duckdb.duckdb.CatalogException: Catalog Error: Schema with name refined does not exist!
[2025-03-30T12:43:00.541+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-30T12:43:00.543+0000] {logging_mixin.py:190} INFO - Task start:2025-03-30 12:43:00.229719+00:00 end:2025-03-30 12:43:00.539024+00:00 duration:0.309305
[2025-03-30T12:43:00.544+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_refined> dag:<DAG: ecommerce_data_pipeline> dagrun:<DagRun ecommerce_data_pipeline @ 2025-03-30 12:42:50.019425+00:00: manual__2025-03-30T12:42:50.019425+00:00, state:running, queued_at: 2025-03-30 12:42:50.029776+00:00. externally triggered: True>
[2025-03-30T12:43:00.545+0000] {logging_mixin.py:190} INFO - Failure caused by Catalog Error: Schema with name refined does not exist!
[2025-03-30T12:43:00.545+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=ecommerce_data_pipeline, task_id=load_refined, run_id=manual__2025-03-30T12:42:50.019425+00:00, execution_date=20250330T124250, start_date=20250330T124300, end_date=20250330T124300
[2025-03-30T12:43:00.592+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T12:43:00.593+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 746 for task load_refined (Catalog Error: Schema with name refined does not exist!; 801)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Gestioncommands.py", line 110, in load_refined
    with duckdb.connect(DB_PATH) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Gestioncommands.py", line 112, in load_refined
    conn.execute("""
duckdb.duckdb.CatalogException: Catalog Error: Schema with name refined does not exist!
[2025-03-30T12:43:00.624+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-30T12:43:00.661+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T12:43:00.664+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
