[2025-03-30T12:15:08.423+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T12:15:08.716+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_data_pipeline.store_data scheduled__2025-03-30T12:10:00+00:00 [queued]>
[2025-03-30T12:15:08.731+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_data_pipeline.store_data scheduled__2025-03-30T12:10:00+00:00 [queued]>
[2025-03-30T12:15:08.744+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-30T12:15:08.767+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): store_data> on 2025-03-30 12:10:00+00:00
[2025-03-30T12:15:08.779+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=197) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-30T12:15:08.784+0000] {standard_task_runner.py:72} INFO - Started process 203 to run task
[2025-03-30T12:15:08.785+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_data_pipeline', 'store_data', 'scheduled__2025-03-30T12:10:00+00:00', '--job-id', '662', '--raw', '--subdir', 'DAGS_FOLDER/Gestioncommands.py', '--cfg-path', '/tmp/tmpoz9ct40m']
[2025-03-30T12:15:08.787+0000] {standard_task_runner.py:105} INFO - Job 662: Subtask store_data
[2025-03-30T12:15:08.879+0000] {task_command.py:467} INFO - Running <TaskInstance: ecommerce_data_pipeline.store_data scheduled__2025-03-30T12:10:00+00:00 [running]> on host 778b271a0247
[2025-03-30T12:15:09.041+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecommerce_data_pipeline' AIRFLOW_CTX_TASK_ID='store_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T12:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T12:10:00+00:00'
[2025-03-30T12:15:09.044+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-30T12:15:09.044+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-30T12:15:09.045+0000] {logging_mixin.py:190} INFO - Current task name:store_data state:running start_date:2025-03-30 12:15:08.717809+00:00
[2025-03-30T12:15:09.046+0000] {logging_mixin.py:190} INFO - Dag name:ecommerce_data_pipeline and current dag run status:running
[2025-03-30T12:15:09.047+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T12:15:09.063+0000] {Gestioncommands.py:44} INFO - Début du stockage incrémental...
[2025-03-30T12:15:09.094+0000] {Gestioncommands.py:102} ERROR - Erreur de stockage : IO Error: Could not set lock on file "/opt/***/***\Db\ecommerce.db": Conflicting lock is held in /usr/local/bin/python3.12 (PID 204). See also https://duckdb.org/docs/connect/concurrency
[2025-03-30T12:15:09.095+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Gestioncommands.py", line 259, in task_store_data
    store_data(csv_content)
  File "/opt/airflow/dags/Gestioncommands.py", line 61, in store_data
    with duckdb.connect(DB_PATH) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Could not set lock on file "/opt/***/***\Db\ecommerce.db": Conflicting lock is held in /usr/local/bin/python3.12 (PID 204). See also https://duckdb.org/docs/connect/concurrency
[2025-03-30T12:15:09.121+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-30T12:15:09.122+0000] {logging_mixin.py:190} INFO - Task start:2025-03-30 12:15:08.717809+00:00 end:2025-03-30 12:15:09.120222+00:00 duration:0.402413
[2025-03-30T12:15:09.122+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): store_data> dag:<DAG: ecommerce_data_pipeline> dagrun:<DagRun ecommerce_data_pipeline @ 2025-03-30 12:10:00+00:00: scheduled__2025-03-30T12:10:00+00:00, state:running, queued_at: 2025-03-30 12:15:00.222816+00:00. externally triggered: False>
[2025-03-30T12:15:09.123+0000] {logging_mixin.py:190} INFO - Failure caused by IO Error: Could not set lock on file "/opt/***/***\Db\ecommerce.db": Conflicting lock is held in /usr/local/bin/python3.12 (PID 204). See also https://duckdb.org/docs/connect/concurrency
[2025-03-30T12:15:09.124+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=ecommerce_data_pipeline, task_id=store_data, run_id=scheduled__2025-03-30T12:10:00+00:00, execution_date=20250330T121000, start_date=20250330T121508, end_date=20250330T121509
[2025-03-30T12:15:09.177+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T12:15:09.178+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 662 for task store_data (IO Error: Could not set lock on file "/opt/***/***\Db\ecommerce.db": Conflicting lock is held in /usr/local/bin/python3.12 (PID 204). See also https://duckdb.org/docs/connect/concurrency; 203)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Gestioncommands.py", line 259, in task_store_data
    store_data(csv_content)
  File "/opt/airflow/dags/Gestioncommands.py", line 61, in store_data
    with duckdb.connect(DB_PATH) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Could not set lock on file "/opt/***/***\Db\ecommerce.db": Conflicting lock is held in /usr/local/bin/python3.12 (PID 204). See also https://duckdb.org/docs/connect/concurrency
[2025-03-30T12:15:09.244+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-30T12:15:09.264+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
