[2025-03-29T18:11:34.602+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T18:11:34.981+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Etl_pipeline_order_management.store_data scheduled__2025-03-29T17:59:00+00:00 [queued]>
[2025-03-29T18:11:34.999+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Etl_pipeline_order_management.store_data scheduled__2025-03-29T17:59:00+00:00 [queued]>
[2025-03-29T18:11:35.000+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-29T18:11:35.033+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): store_data> on 2025-03-29 17:59:00+00:00
[2025-03-29T18:11:35.049+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1100) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-29T18:11:35.055+0000] {standard_task_runner.py:72} INFO - Started process 1114 to run task
[2025-03-29T18:11:35.056+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Etl_pipeline_order_management', 'store_data', 'scheduled__2025-03-29T17:59:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/Gestioncommands.py', '--cfg-path', '/tmp/tmpqce6z298']
[2025-03-29T18:11:35.058+0000] {standard_task_runner.py:105} INFO - Job 146: Subtask store_data
[2025-03-29T18:11:35.169+0000] {task_command.py:467} INFO - Running <TaskInstance: Etl_pipeline_order_management.store_data scheduled__2025-03-29T17:59:00+00:00 [running]> on host 499696d11f67
[2025-03-29T18:11:35.383+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Etl_pipeline_order_management' AIRFLOW_CTX_TASK_ID='store_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T17:59:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-29T17:59:00+00:00'
[2025-03-29T18:11:35.387+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-29T18:11:35.388+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-29T18:11:35.389+0000] {logging_mixin.py:190} INFO - Current task name:store_data state:running start_date:2025-03-29 18:11:34.982188+00:00
[2025-03-29T18:11:35.390+0000] {logging_mixin.py:190} INFO - Dag name:Etl_pipeline_order_management and current dag run status:running
[2025-03-29T18:11:35.391+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-29T18:11:35.393+0000] {Gestioncommands.py:44} INFO - Retrieving CSV data from XCom...
[2025-03-29T18:11:35.543+0000] {Gestioncommands.py:125} ERROR - Error during storing data: IO Error: Could not set lock on file "/opt/***/Db\ecommerce.db": Conflicting lock is held in /usr/local/bin/python3.12 (PID 1110). See also https://duckdb.org/docs/connect/concurrency
[2025-03-29T18:11:35.547+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Gestioncommands.py", line 58, in store_data
    with duckdb.connect(DB_PATH) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Could not set lock on file "/opt/***/Db\ecommerce.db": Conflicting lock is held in /usr/local/bin/python3.12 (PID 1110). See also https://duckdb.org/docs/connect/concurrency
[2025-03-29T18:11:35.594+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-29T18:11:35.596+0000] {logging_mixin.py:190} INFO - Task start:2025-03-29 18:11:34.982188+00:00 end:2025-03-29 18:11:35.592564+00:00 duration:0.610376
[2025-03-29T18:11:35.597+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): store_data> dag:<DAG: Etl_pipeline_order_management> dagrun:<DagRun Etl_pipeline_order_management @ 2025-03-29 17:59:00+00:00: scheduled__2025-03-29T17:59:00+00:00, state:running, queued_at: 2025-03-29 18:00:00.422900+00:00. externally triggered: False>
[2025-03-29T18:11:35.599+0000] {logging_mixin.py:190} INFO - Failure caused by IO Error: Could not set lock on file "/opt/***/Db\ecommerce.db": Conflicting lock is held in /usr/local/bin/python3.12 (PID 1110). See also https://duckdb.org/docs/connect/concurrency
[2025-03-29T18:11:35.600+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=Etl_pipeline_order_management, task_id=store_data, run_id=scheduled__2025-03-29T17:59:00+00:00, execution_date=20250329T175900, start_date=20250329T181134, end_date=20250329T181135
[2025-03-29T18:11:35.676+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-29T18:11:35.679+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 146 for task store_data (IO Error: Could not set lock on file "/opt/***/Db\ecommerce.db": Conflicting lock is held in /usr/local/bin/python3.12 (PID 1110). See also https://duckdb.org/docs/connect/concurrency; 1114)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Gestioncommands.py", line 58, in store_data
    with duckdb.connect(DB_PATH) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Could not set lock on file "/opt/***/Db\ecommerce.db": Conflicting lock is held in /usr/local/bin/python3.12 (PID 1110). See also https://duckdb.org/docs/connect/concurrency
[2025-03-29T18:11:35.759+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-29T18:11:35.824+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-29T18:11:35.828+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
